import { Sora, Inter } from "next/font/google";
import "./globals.css";

import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ['latin'] });
const sora = Sora({ subsets: ['latin'] });

export const metadata = {
  title: "Falcon Fresh Grocery Website",
  description: "Generated by create next app",
};

console.log("server is running")

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  antialiased`}
      >
         <NextTopLoader color="#B21F78" />
     
        {children}
      
      </body>
    </html>
  );
}
